package edu.hbuas.netdisk.model;

import java.io.Serializable;

/**
 * 网盘用户信息表 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	@Override
	public String toString() {
		return "User [username=" + username + ", password=" + password + ", sex=" + sex + ", age=" + age + ", tel="
				+ tel + ", email=" + email + "]";
	}

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 网盘账户. */
	private String username;

	/** 网盘密码. */
	private String password;

	/** 性别. */
	private String sex;

	/** 年龄. */
	private Integer age;

	/** 电话. */
	private String tel;

	/** 邮箱. */
	private String email;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public User() {
	}

	/**
	 * 网盘账户 傪愝掕偟傑偡.
	 * 
	 * @param username
	 *            网盘账户
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 网盘账户 傪庢摼偟傑偡.
	 * 
	 * @return 网盘账户
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * 网盘密码 傪愝掕偟傑偡.
	 * 
	 * @param password
	 *            网盘密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 网盘密码 傪庢摼偟傑偡.
	 * 
	 * @return 网盘密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 性别 傪愝掕偟傑偡.
	 * 
	 * @param sex
	 *            性别
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * 性别 傪庢摼偟傑偡.
	 * 
	 * @return 性别
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * 年龄 傪愝掕偟傑偡.
	 * 
	 * @param age
	 *            年龄
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * 年龄 傪庢摼偟傑偡.
	 * 
	 * @return 年龄
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * 电话 傪愝掕偟傑偡.
	 * 
	 * @param tel
	 *            电话
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * 电话 傪庢摼偟傑偡.
	 * 
	 * @return 电话
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * 邮箱 傪愝掕偟傑偡.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 邮箱 傪庢摼偟傑偡.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((username == null) ? 0 : username.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (username == null) {
			if (other.username != null) {
				return false;
			}
		} else if (!username.equals(other.username)) {
			return false;
		}

		return true;
	}

}
